apiVersion:  apps/v1
kind: Deployment
metadata:
  name: kubernetes-rails-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: rails-app
    template:
        metadata:
            labels:
                app: rails-app
        spec:
            containers:
            - env:
              - name: PORT
                value: "3000"
              envFrom:
              - configMapRef:
                  name: env-var
              - image: tomfern/dockerizing-ruby-drkiq:latest
                imagePullPolicy: IfNotPresent
                name: rails-app
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-rails-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: rails-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
---
apiVersion: v1
kind: Ingress 
metadata: 
  name: frontend-ingress 
spec:
  rules: 
  - http: 
       paths: 
       - path: /api 
       backend: 
         serviceName: frontend-svsvc
         servicePort: 8000
